// Every source that can change Q949 allocation, operation serialization,
// Fiat-Shamir sampling, support replay, or evidence acceptance belongs here.
pub(super) const SOURCES: &[(&str, &[u8])] = &[
    ("Cargo.toml", include_bytes!("../../../Cargo.toml")),
    ("Cargo.lock", include_bytes!("../../../Cargo.lock")),
    ("rust-toolchain", include_bytes!("../../../rust-toolchain")),
    ("src/lib.rs", include_bytes!("../../lib.rs")),
    ("src/circuit.rs", include_bytes!("../../circuit.rs")),
    ("src/sim.rs", include_bytes!("../../sim.rs")),
    (
        "src/weierstrass_elliptic_curve.rs",
        include_bytes!("../../weierstrass_elliptic_curve.rs"),
    ),
    ("src/point_add/mod.rs", include_bytes!("../mod.rs")),
    ("src/point_add/emit.rs", include_bytes!("../emit.rs")),
    ("src/point_add/venting.rs", include_bytes!("../venting.rs")),
    ("src/point_add/trailmix_port/mod.rs", include_bytes!("mod.rs")),
    (
        "src/point_add/trailmix_port/q949_source_manifest.rs",
        include_bytes!("q949_source_manifest.rs"),
    ),
    (
        "src/point_add/trailmix_port/circuit.rs",
        include_bytes!("circuit.rs"),
    ),
    (
        "src/point_add/trailmix_port/mod_arith.rs",
        include_bytes!("mod_arith.rs"),
    ),
    (
        "src/point_add/trailmix_port/rfold_mbu.rs",
        include_bytes!("rfold_mbu.rs"),
    ),
    (
        "src/point_add/trailmix_port/arith/compare.rs",
        include_bytes!("arith/compare.rs"),
    ),
    (
        "src/point_add/trailmix_port/arith/const_add.rs",
        include_bytes!("arith/const_add.rs"),
    ),
    (
        "src/point_add/trailmix_port/arith/cuccaro.rs",
        include_bytes!("arith/cuccaro.rs"),
    ),
    (
        "src/point_add/trailmix_port/arith/gidney_const_adder.rs",
        include_bytes!("arith/gidney_const_adder.rs"),
    ),
    (
        "src/point_add/trailmix_port/arith/khattar_gidney.rs",
        include_bytes!("arith/khattar_gidney.rs"),
    ),
    (
        "src/point_add/trailmix_port/arith/mcx.rs",
        include_bytes!("arith/mcx.rs"),
    ),
    (
        "src/point_add/trailmix_port/arith/qshift_sub.rs",
        include_bytes!("arith/qshift_sub.rs"),
    ),
    (
        "src/point_add/trailmix_port/arith/ripple_add.rs",
        include_bytes!("arith/ripple_add.rs"),
    ),
    (
        "src/point_add/trailmix_port/arith/shift.rs",
        include_bytes!("arith/shift.rs"),
    ),
    (
        "src/point_add/trailmix_port/ec/point_add.rs",
        include_bytes!("ec/point_add.rs"),
    ),
    (
        "src/point_add/trailmix_port/inversion/shrunken_pz_primitives.rs",
        include_bytes!("inversion/shrunken_pz_primitives.rs"),
    ),
    (
        "src/point_add/trailmix_port/inversion/shrunken_pz_schedule.rs",
        include_bytes!("inversion/shrunken_pz_schedule.rs"),
    ),
    (
        "src/point_add/trailmix_port/inversion/shrunken_pz_state_machine.rs",
        include_bytes!("inversion/shrunken_pz_state_machine.rs"),
    ),
    (
        "src/point_add/trailmix_port/inversion/q944_dirty_parity_microkernels.rs",
        include_bytes!("inversion/q944_dirty_parity_microkernels.rs"),
    ),
    (
        "src/point_add/trailmix_port/inversion/q945_local_hosts.rs",
        include_bytes!("inversion/q945_local_hosts.rs"),
    ),
    (
        "src/point_add/trailmix_port/inversion/q949_robust_envelope.rs",
        include_bytes!("inversion/q949_robust_envelope.rs"),
    ),
    (
        "src/point_add/trailmix_port/inversion/q949_robust_envelope_data.rs",
        include_bytes!("inversion/q949_robust_envelope_data.rs"),
    ),
    (
        "src/point_add/trailmix_port/inversion/q949_robust_projection_metadata.json",
        include_bytes!("inversion/q949_robust_projection_metadata.json"),
    ),
    (
        "src/bin/q949_affine_counter_proof.rs",
        include_bytes!("../../bin/q949_affine_counter_proof.rs"),
    ),
    (
        "src/bin/q949_affine_counter_profile.rs",
        include_bytes!("../../bin/q949_affine_counter_profile.rs"),
    ),
    (
        "src/bin/q949_robust_common/mod.rs",
        include_bytes!("../../bin/q949_robust_common/mod.rs"),
    ),
    (
        "src/bin/q949_robust_common/diagnostics.rs",
        include_bytes!("../../bin/q949_robust_common/diagnostics.rs"),
    ),
    (
        "src/bin/q949_robust_symmetric_schedule_proof.rs",
        include_bytes!("../../bin/q949_robust_symmetric_schedule_proof.rs"),
    ),
    (
        "src/bin/q949_robust_symmetric_schedule_count.rs",
        include_bytes!("../../bin/q949_robust_symmetric_schedule_count.rs"),
    ),
    (
        "src/bin/q949_robust_symmetric_schedule_census.rs",
        include_bytes!("../../bin/q949_robust_symmetric_schedule_census.rs"),
    ),
    (
        "src/bin/q949_robust_symmetric_schedule_profile.rs",
        include_bytes!("../../bin/q949_robust_symmetric_schedule_profile.rs"),
    ),
    (
        "src/bin/q949_robust_evidence_selftest.rs",
        include_bytes!("../../bin/q949_robust_evidence_selftest.rs"),
    ),
    (
        "src/bin/hardened_lifetime_helper_proof.rs",
        include_bytes!("../../bin/hardened_lifetime_helper_proof.rs"),
    ),
    (
        "src/bin/hardened_peak_quadrants_count.rs",
        include_bytes!("../../bin/hardened_peak_quadrants_count.rs"),
    ),
    (
        "src/bin/q948_borrowed_transcript_proof.rs",
        include_bytes!("../../bin/q948_borrowed_transcript_proof.rs"),
    ),
    (
        "src/bin/q948_borrowed_transcript_count.rs",
        include_bytes!("../../bin/q948_borrowed_transcript_count.rs"),
    ),
    (
        "src/bin/q948_borrowed_transcript_census.rs",
        include_bytes!("../../bin/q948_borrowed_transcript_census.rs"),
    ),
    (
        "src/bin/q948_borrowed_transcript_profile.rs",
        include_bytes!("../../bin/q948_borrowed_transcript_profile.rs"),
    ),
    (
        "src/bin/six_stream_borrowed_relational_proof.rs",
        include_bytes!("../../bin/six_stream_borrowed_relational_proof.rs"),
    ),
    (
        "src/bin/six_stream_relational_peak_quadrants.rs",
        include_bytes!("../../bin/six_stream_relational_peak_quadrants.rs"),
    ),
    (
        "src/bin/six_stream_borrowed_relational_census.rs",
        include_bytes!("../../bin/six_stream_borrowed_relational_census.rs"),
    ),
    (
        "src/bin/six_stream_borrow_only_count.rs",
        include_bytes!("../../bin/six_stream_borrow_only_count.rs"),
    ),
    (
        "src/bin/six_stream_borrow_only_census.rs",
        include_bytes!("../../bin/six_stream_borrow_only_census.rs"),
    ),
    (
        "src/bin/six_stream_borrow_only_deficit_histogram.rs",
        include_bytes!("../../bin/six_stream_borrow_only_deficit_histogram.rs"),
    ),
    (
        "src/bin/q948_exact_capacity_proof.rs",
        include_bytes!("../../bin/q948_exact_capacity_proof.rs"),
    ),
    (
        "src/bin/q948_exact_capacity_count.rs",
        include_bytes!("../../bin/q948_exact_capacity_count.rs"),
    ),
    (
        "src/bin/q948_exact_capacity_census.rs",
        include_bytes!("../../bin/q948_exact_capacity_census.rs"),
    ),
    (
        "src/bin/q948_exact_capacity_profile.rs",
        include_bytes!("../../bin/q948_exact_capacity_profile.rs"),
    ),
    (
        "src/bin/q948_exact_capacity_peak_diagnostic.rs",
        include_bytes!("../../bin/q948_exact_capacity_peak_diagnostic.rs"),
    ),
    (
        "src/bin/q949_peak_safe_checkpoint.rs",
        include_bytes!("../../bin/q949_peak_safe_checkpoint.rs"),
    ),
    (
        "tools/q949_solve_adaptive_envelope.py",
        include_bytes!("../../../tools/q949_solve_adaptive_envelope.py"),
    ),
    (
        "tools/q949_generate_envelope.py",
        include_bytes!("../../../tools/q949_generate_envelope.py"),
    ),
    (
        "wmi/q949-six-stream-solve-generate.sbatch",
        include_bytes!("../../../wmi/q949-six-stream-solve-generate.sbatch"),
    ),
    (
        "wmi/q949-six-stream-validate-nonce5.sbatch",
        include_bytes!("../../../wmi/q949-six-stream-validate-nonce5.sbatch"),
    ),
    (
        "wmi/six-stream-borrowed-relational-gptcodex.sbatch",
        include_bytes!("../../../wmi/six-stream-borrowed-relational-gptcodex.sbatch"),
    ),
    (
        "wmi/six-stream-borrowed-relational-fresh-gptcodex.sbatch",
        include_bytes!("../../../wmi/six-stream-borrowed-relational-fresh-gptcodex.sbatch"),
    ),
    (
        "wmi/six-stream-borrow-only-fresh-gptcodex.sbatch",
        include_bytes!("../../../wmi/six-stream-borrow-only-fresh-gptcodex.sbatch"),
    ),
    (
        "wmi/six-stream-borrow-only-deficit-histogram.sbatch",
        include_bytes!("../../../wmi/six-stream-borrow-only-deficit-histogram.sbatch"),
    ),
    (
        "wmi/q948-exact-capacity-max-subset.sbatch",
        include_bytes!("../../../wmi/q948-exact-capacity-max-subset.sbatch"),
    ),
    (
        "wmi/q948-exact-capacity-solve-generate.sbatch",
        include_bytes!("../../../wmi/q948-exact-capacity-solve-generate.sbatch"),
    ),
    (
        "wmi/q948-exact-capacity-checkpoint.sbatch",
        include_bytes!("../../../wmi/q948-exact-capacity-checkpoint.sbatch"),
    ),
    (
        "wmi/q948-exact-capacity-peak-diagnostic.sbatch",
        include_bytes!("../../../wmi/q948-exact-capacity-peak-diagnostic.sbatch"),
    ),
    (
        "wmi/q949-peak-safe-checkpoint.sbatch",
        include_bytes!("../../../wmi/q949-peak-safe-checkpoint.sbatch"),
    ),
    (
        "wmi/q948-peak-safe-passenger-quadrants.sbatch",
        include_bytes!("../../../wmi/q948-peak-safe-passenger-quadrants.sbatch"),
    ),
    (
        "src/bin/q948_direct_hclz_peak_guard_proof.rs",
        include_bytes!("../../bin/q948_direct_hclz_peak_guard_proof.rs"),
    ),
    (
        "src/bin/q948_direct_hclz_peak_quadrants.rs",
        include_bytes!("../../bin/q948_direct_hclz_peak_quadrants.rs"),
    ),
    (
        "wmi/q948-direct-hclz-peak-guard.sbatch",
        include_bytes!("../../../wmi/q948-direct-hclz-peak-guard.sbatch"),
    ),
    (
        "wmi/q949-target681-force-71530-selector.sbatch",
        include_bytes!("../../../wmi/q949-target681-force-71530-selector.sbatch"),
    ),
    (
        "src/bin/q948_direct_hclz_count.rs",
        include_bytes!("../../bin/q948_direct_hclz_count.rs"),
    ),
    (
        "src/bin/q948_direct_hclz_fresh_census.rs",
        include_bytes!("../../bin/q948_direct_hclz_fresh_census.rs"),
    ),
    (
        "wmi/q948-direct-hclz-fresh-nonce24.sbatch",
        include_bytes!("../../../wmi/q948-direct-hclz-fresh-nonce24.sbatch"),
    ),
    (
        "wmi/q948-peak-neutral-repair-nonce24.sbatch",
        include_bytes!("../../../wmi/q948-peak-neutral-repair-nonce24.sbatch"),
    ),
    (
        "src/bin/q947_passenger_direct_hclz_common/mod.rs",
        include_bytes!("../../bin/q947_passenger_direct_hclz_common/mod.rs"),
    ),
    (
        "src/bin/q947_passenger_direct_hclz_proof.rs",
        include_bytes!("../../bin/q947_passenger_direct_hclz_proof.rs"),
    ),
    (
        "src/bin/q947_passenger_direct_hclz_count.rs",
        include_bytes!("../../bin/q947_passenger_direct_hclz_count.rs"),
    ),
    (
        "src/bin/q947_passenger_direct_hclz_profile.rs",
        include_bytes!("../../bin/q947_passenger_direct_hclz_profile.rs"),
    ),
    (
        "src/bin/q946_second_release_common/mod.rs",
        include_bytes!("../../bin/q946_second_release_common/mod.rs"),
    ),
    (
        "src/bin/q946_second_release_proof.rs",
        include_bytes!("../../bin/q946_second_release_proof.rs"),
    ),
    (
        "src/bin/q946_second_release_count.rs",
        include_bytes!("../../bin/q946_second_release_count.rs"),
    ),
    (
        "src/bin/q946_second_release_census.rs",
        include_bytes!("../../bin/q946_second_release_census.rs"),
    ),
    (
        "src/bin/q945_local_hosts_common/mod.rs",
        include_bytes!("../../bin/q945_local_hosts_common/mod.rs"),
    ),
    (
        "src/bin/q945_local_hosts_proof.rs",
        include_bytes!("../../bin/q945_local_hosts_proof.rs"),
    ),
    (
        "src/bin/q945_local_hosts_count.rs",
        include_bytes!("../../bin/q945_local_hosts_count.rs"),
    ),
    (
        "src/bin/q945_host_support_census.rs",
        include_bytes!("../../bin/q945_host_support_census.rs"),
    ),
    (
        "wmi/q947-passenger-direct-hclz-proof-count.sbatch",
        include_bytes!("../../../wmi/q947-passenger-direct-hclz-proof-count.sbatch"),
    ),
    (
        "wmi/q947-passenger-direct-hclz-profile.sbatch",
        include_bytes!("../../../wmi/q947-passenger-direct-hclz-profile.sbatch"),
    ),
    (
        "wmi/q947-gpu-emitted-parity.sbatch",
        include_bytes!("../../../wmi/q947-gpu-emitted-parity.sbatch"),
    ),
    (
        "wmi/q947-gpu-parity.sbatch",
        include_bytes!("../../../wmi/q947-gpu-parity.sbatch"),
    ),
    (
        "wmi/q947-gpu-search-array.sbatch",
        include_bytes!("../../../wmi/q947-gpu-search-array.sbatch"),
    ),
    (
        "wmi/q946-second-release-proof-count.sbatch",
        include_bytes!("../../../wmi/q946-second-release-proof-count.sbatch"),
    ),
    (
        "wmi/q946-second-release-deficit-census.sbatch",
        include_bytes!("../../../wmi/q946-second-release-deficit-census.sbatch"),
    ),
    (
        "wmi/q945-local-hosts-structural-proof-count.sbatch",
        include_bytes!("../../../wmi/q945-local-hosts-structural-proof-count.sbatch"),
    ),
    (
        "wmi/q945-host-support-census.sbatch",
        include_bytes!("../../../wmi/q945-host-support-census.sbatch"),
    ),
    (
        "wmi/q948_exact_capacity_selected_training.json",
        include_bytes!("../../../wmi/q948_exact_capacity_selected_training.json"),
    ),
];
